// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTEverything;

@interface FLTEverything : NSObject
+ (instancetype)makeWithABool:(nullable NSNumber *)aBool
    aInt:(nullable NSNumber *)aInt
    aDouble:(nullable NSNumber *)aDouble
    aString:(nullable NSString *)aString
    aList:(nullable NSArray *)aList
    aMap:(nullable NSDictionary *)aMap
    nestedList:(nullable NSArray<NSArray<NSNumber *> *> *)nestedList
    mapWithAnnotations:(nullable NSDictionary<NSString *, NSString *> *)mapWithAnnotations;
@property(nonatomic, strong, nullable) NSNumber * aBool;
@property(nonatomic, strong, nullable) NSNumber * aInt;
@property(nonatomic, strong, nullable) NSNumber * aDouble;
@property(nonatomic, copy, nullable) NSString * aString;
@property(nonatomic, strong, nullable) NSArray * aList;
@property(nonatomic, strong, nullable) NSDictionary * aMap;
@property(nonatomic, strong, nullable) NSArray<NSArray<NSNumber *> *> * nestedList;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * mapWithAnnotations;
@end

/// The codec used by FLTHostEverything.
NSObject<FlutterMessageCodec> *FLTHostEverythingGetCodec(void);

@protocol FLTHostEverything
/// @return `nil` only when `error != nil`.
- (nullable FLTEverything *)giveMeEverythingWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FLTEverything *)echoEverything:(FLTEverything *)everything error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTHostEverythingSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTHostEverything> *_Nullable api);

/// The codec used by FLTFlutterEverything.
NSObject<FlutterMessageCodec> *FLTFlutterEverythingGetCodec(void);

@interface FLTFlutterEverything : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)giveMeEverythingFlutterWithCompletion:(void(^)(FLTEverything *_Nullable, NSError *_Nullable))completion;
- (void)echoFlutterEverything:(FLTEverything *)everything completion:(void(^)(FLTEverything *_Nullable, NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
