// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "AllTypesPigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface FLTEverything ()
+ (FLTEverything *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FLTEverything
+ (instancetype)makeWithABool:(nullable NSNumber *)aBool
    aInt:(nullable NSNumber *)aInt
    aDouble:(nullable NSNumber *)aDouble
    aString:(nullable NSString *)aString
    aList:(nullable NSArray *)aList
    aMap:(nullable NSDictionary *)aMap
    nestedList:(nullable NSArray<NSArray<NSNumber *> *> *)nestedList
    mapWithAnnotations:(nullable NSDictionary<NSString *, NSString *> *)mapWithAnnotations {
  FLTEverything* pigeonResult = [[FLTEverything alloc] init];
  pigeonResult.aBool = aBool;
  pigeonResult.aInt = aInt;
  pigeonResult.aDouble = aDouble;
  pigeonResult.aString = aString;
  pigeonResult.aList = aList;
  pigeonResult.aMap = aMap;
  pigeonResult.nestedList = nestedList;
  pigeonResult.mapWithAnnotations = mapWithAnnotations;
  return pigeonResult;
}
+ (FLTEverything *)fromMap:(NSDictionary *)dict {
  FLTEverything *pigeonResult = [[FLTEverything alloc] init];
  pigeonResult.aBool = GetNullableObject(dict, @"aBool");
  pigeonResult.aInt = GetNullableObject(dict, @"aInt");
  pigeonResult.aDouble = GetNullableObject(dict, @"aDouble");
  pigeonResult.aString = GetNullableObject(dict, @"aString");
  pigeonResult.aList = GetNullableObject(dict, @"aList");
  pigeonResult.aMap = GetNullableObject(dict, @"aMap");
  pigeonResult.nestedList = GetNullableObject(dict, @"nestedList");
  pigeonResult.mapWithAnnotations = GetNullableObject(dict, @"mapWithAnnotations");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.aBool ? self.aBool : [NSNull null]), @"aBool", (self.aInt ? self.aInt : [NSNull null]), @"aInt", (self.aDouble ? self.aDouble : [NSNull null]), @"aDouble", (self.aString ? self.aString : [NSNull null]), @"aString", (self.aList ? self.aList : [NSNull null]), @"aList", (self.aMap ? self.aMap : [NSNull null]), @"aMap", (self.nestedList ? self.nestedList : [NSNull null]), @"nestedList", (self.mapWithAnnotations ? self.mapWithAnnotations : [NSNull null]), @"mapWithAnnotations", nil];
}
@end

@interface FLTHostEverythingCodecReader : FlutterStandardReader
@end
@implementation FLTHostEverythingCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTEverything fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTHostEverythingCodecWriter : FlutterStandardWriter
@end
@implementation FLTHostEverythingCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTEverything class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTHostEverythingCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTHostEverythingCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTHostEverythingCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTHostEverythingCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTHostEverythingGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTHostEverythingCodecReaderWriter *readerWriter = [[FLTHostEverythingCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FLTHostEverythingSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTHostEverything> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.HostEverything.giveMeEverything"
        binaryMessenger:binaryMessenger
        codec:FLTHostEverythingGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(giveMeEverythingWithError:)], @"FLTHostEverything api (%@) doesn't respond to @selector(giveMeEverythingWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTEverything *output = [api giveMeEverythingWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.HostEverything.echo"
        binaryMessenger:binaryMessenger
        codec:FLTHostEverythingGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(echoEverything:error:)], @"FLTHostEverything api (%@) doesn't respond to @selector(echoEverything:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FLTEverything *arg_everything = args[0];
        FlutterError *error;
        FLTEverything *output = [api echoEverything:arg_everything error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTFlutterEverythingCodecReader : FlutterStandardReader
@end
@implementation FLTFlutterEverythingCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTEverything fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTFlutterEverythingCodecWriter : FlutterStandardWriter
@end
@implementation FLTFlutterEverythingCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTEverything class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTFlutterEverythingCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTFlutterEverythingCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTFlutterEverythingCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTFlutterEverythingCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTFlutterEverythingGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTFlutterEverythingCodecReaderWriter *readerWriter = [[FLTFlutterEverythingCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


@interface FLTFlutterEverything ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLTFlutterEverything

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)giveMeEverythingFlutterEverything:(FLTEverything *)arg_everything completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.FlutterEverything.giveMeEverythingFlutter"
      binaryMessenger:self.binaryMessenger
      codec:FLTFlutterEverythingGetCodec()];
  [channel sendMessage:@[arg_everything] reply:^(id reply) {
    completion(nil);
  }];
}
@end
